// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: rpkm67/store/object/v1/object.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ObjectService_FindByKey_FullMethodName   = "/rpkm67.file.image.v1.ObjectService/FindByKey"
	ObjectService_Upload_FullMethodName      = "/rpkm67.file.image.v1.ObjectService/Upload"
	ObjectService_DeleteByKey_FullMethodName = "/rpkm67.file.image.v1.ObjectService/DeleteByKey"
)

// ObjectServiceClient is the client API for ObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectServiceClient interface {
	FindByKey(ctx context.Context, in *FindByKeyObjectRequest, opts ...grpc.CallOption) (*FindByKeyObjectResponse, error)
	Upload(ctx context.Context, in *UploadObjectRequest, opts ...grpc.CallOption) (*UploadObjectResponse, error)
	DeleteByKey(ctx context.Context, in *DeleteByKeyObjectRequest, opts ...grpc.CallOption) (*DeleteByKeyObjectResponse, error)
}

type objectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectServiceClient(cc grpc.ClientConnInterface) ObjectServiceClient {
	return &objectServiceClient{cc}
}

func (c *objectServiceClient) FindByKey(ctx context.Context, in *FindByKeyObjectRequest, opts ...grpc.CallOption) (*FindByKeyObjectResponse, error) {
	out := new(FindByKeyObjectResponse)
	err := c.cc.Invoke(ctx, ObjectService_FindByKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectServiceClient) Upload(ctx context.Context, in *UploadObjectRequest, opts ...grpc.CallOption) (*UploadObjectResponse, error) {
	out := new(UploadObjectResponse)
	err := c.cc.Invoke(ctx, ObjectService_Upload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectServiceClient) DeleteByKey(ctx context.Context, in *DeleteByKeyObjectRequest, opts ...grpc.CallOption) (*DeleteByKeyObjectResponse, error) {
	out := new(DeleteByKeyObjectResponse)
	err := c.cc.Invoke(ctx, ObjectService_DeleteByKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectServiceServer is the server API for ObjectService service.
// All implementations must embed UnimplementedObjectServiceServer
// for forward compatibility
type ObjectServiceServer interface {
	FindByKey(context.Context, *FindByKeyObjectRequest) (*FindByKeyObjectResponse, error)
	Upload(context.Context, *UploadObjectRequest) (*UploadObjectResponse, error)
	DeleteByKey(context.Context, *DeleteByKeyObjectRequest) (*DeleteByKeyObjectResponse, error)
	mustEmbedUnimplementedObjectServiceServer()
}

// UnimplementedObjectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedObjectServiceServer struct {
}

func (UnimplementedObjectServiceServer) FindByKey(context.Context, *FindByKeyObjectRequest) (*FindByKeyObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByKey not implemented")
}
func (UnimplementedObjectServiceServer) Upload(context.Context, *UploadObjectRequest) (*UploadObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedObjectServiceServer) DeleteByKey(context.Context, *DeleteByKeyObjectRequest) (*DeleteByKeyObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteByKey not implemented")
}
func (UnimplementedObjectServiceServer) mustEmbedUnimplementedObjectServiceServer() {}

// UnsafeObjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectServiceServer will
// result in compilation errors.
type UnsafeObjectServiceServer interface {
	mustEmbedUnimplementedObjectServiceServer()
}

func RegisterObjectServiceServer(s grpc.ServiceRegistrar, srv ObjectServiceServer) {
	s.RegisterService(&ObjectService_ServiceDesc, srv)
}

func _ObjectService_FindByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByKeyObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectServiceServer).FindByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectService_FindByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectServiceServer).FindByKey(ctx, req.(*FindByKeyObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectServiceServer).Upload(ctx, req.(*UploadObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectService_DeleteByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByKeyObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectServiceServer).DeleteByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectService_DeleteByKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectServiceServer).DeleteByKey(ctx, req.(*DeleteByKeyObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectService_ServiceDesc is the grpc.ServiceDesc for ObjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpkm67.file.image.v1.ObjectService",
	HandlerType: (*ObjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByKey",
			Handler:    _ObjectService_FindByKey_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _ObjectService_Upload_Handler,
		},
		{
			MethodName: "DeleteByKey",
			Handler:    _ObjectService_DeleteByKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpkm67/store/object/v1/object.proto",
}
