// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpkm67/store/object/v1/object.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_rpkm67_store_object_v1_object_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Object) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// FindByKey
type FindByKeyObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindByKeyObjectRequest) Reset() {
	*x = FindByKeyObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByKeyObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByKeyObjectRequest) ProtoMessage() {}

func (x *FindByKeyObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByKeyObjectRequest.ProtoReflect.Descriptor instead.
func (*FindByKeyObjectRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_store_object_v1_object_proto_rawDescGZIP(), []int{1}
}

type FindByKeyObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object *Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *FindByKeyObjectResponse) Reset() {
	*x = FindByKeyObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByKeyObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByKeyObjectResponse) ProtoMessage() {}

func (x *FindByKeyObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByKeyObjectResponse.ProtoReflect.Descriptor instead.
func (*FindByKeyObjectResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_store_object_v1_object_proto_rawDescGZIP(), []int{2}
}

func (x *FindByKeyObjectResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

// Upload
type UploadObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadObjectRequest) Reset() {
	*x = UploadObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectRequest) ProtoMessage() {}

func (x *UploadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectRequest.ProtoReflect.Descriptor instead.
func (*UploadObjectRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_store_object_v1_object_proto_rawDescGZIP(), []int{3}
}

func (x *UploadObjectRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadObjectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object *Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *UploadObjectResponse) Reset() {
	*x = UploadObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectResponse) ProtoMessage() {}

func (x *UploadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectResponse.ProtoReflect.Descriptor instead.
func (*UploadObjectResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_store_object_v1_object_proto_rawDescGZIP(), []int{4}
}

func (x *UploadObjectResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

// DeleteByKey
type DeleteByKeyObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteByKeyObjectRequest) Reset() {
	*x = DeleteByKeyObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteByKeyObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByKeyObjectRequest) ProtoMessage() {}

func (x *DeleteByKeyObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByKeyObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteByKeyObjectRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_store_object_v1_object_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteByKeyObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteByKeyObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteByKeyObjectResponse) Reset() {
	*x = DeleteByKeyObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteByKeyObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByKeyObjectResponse) ProtoMessage() {}

func (x *DeleteByKeyObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_store_object_v1_object_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByKeyObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteByKeyObjectResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_store_object_v1_object_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteByKeyObjectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpkm67_store_object_v1_object_proto protoreflect.FileDescriptor

var file_rpkm67_store_object_v1_object_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x2c, 0x0a, 0x06, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4b, 0x65, 0x79,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x22, 0x45, 0x0a, 0x13, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a, 0x14, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x2c, 0x0a, 0x18, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xd0,
	0x02, 0x0a, 0x0d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x6a, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x2c, 0x2e,
	0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x72, 0x70,
	0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x06,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x29, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2a, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x70, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x2e,
	0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x4b, 0x65,
	0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f,
	0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x4b, 0x65,
	0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x16, 0x5a, 0x14, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x66, 0x69, 0x6c, 0x65,
	0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpkm67_store_object_v1_object_proto_rawDescOnce sync.Once
	file_rpkm67_store_object_v1_object_proto_rawDescData = file_rpkm67_store_object_v1_object_proto_rawDesc
)

func file_rpkm67_store_object_v1_object_proto_rawDescGZIP() []byte {
	file_rpkm67_store_object_v1_object_proto_rawDescOnce.Do(func() {
		file_rpkm67_store_object_v1_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpkm67_store_object_v1_object_proto_rawDescData)
	})
	return file_rpkm67_store_object_v1_object_proto_rawDescData
}

var file_rpkm67_store_object_v1_object_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpkm67_store_object_v1_object_proto_goTypes = []interface{}{
	(*Object)(nil),                    // 0: rpkm67.file.image.v1.Object
	(*FindByKeyObjectRequest)(nil),    // 1: rpkm67.file.image.v1.FindByKeyObjectRequest
	(*FindByKeyObjectResponse)(nil),   // 2: rpkm67.file.image.v1.FindByKeyObjectResponse
	(*UploadObjectRequest)(nil),       // 3: rpkm67.file.image.v1.UploadObjectRequest
	(*UploadObjectResponse)(nil),      // 4: rpkm67.file.image.v1.UploadObjectResponse
	(*DeleteByKeyObjectRequest)(nil),  // 5: rpkm67.file.image.v1.DeleteByKeyObjectRequest
	(*DeleteByKeyObjectResponse)(nil), // 6: rpkm67.file.image.v1.DeleteByKeyObjectResponse
}
var file_rpkm67_store_object_v1_object_proto_depIdxs = []int32{
	0, // 0: rpkm67.file.image.v1.FindByKeyObjectResponse.object:type_name -> rpkm67.file.image.v1.Object
	0, // 1: rpkm67.file.image.v1.UploadObjectResponse.object:type_name -> rpkm67.file.image.v1.Object
	1, // 2: rpkm67.file.image.v1.ObjectService.FindByKey:input_type -> rpkm67.file.image.v1.FindByKeyObjectRequest
	3, // 3: rpkm67.file.image.v1.ObjectService.Upload:input_type -> rpkm67.file.image.v1.UploadObjectRequest
	5, // 4: rpkm67.file.image.v1.ObjectService.DeleteByKey:input_type -> rpkm67.file.image.v1.DeleteByKeyObjectRequest
	2, // 5: rpkm67.file.image.v1.ObjectService.FindByKey:output_type -> rpkm67.file.image.v1.FindByKeyObjectResponse
	4, // 6: rpkm67.file.image.v1.ObjectService.Upload:output_type -> rpkm67.file.image.v1.UploadObjectResponse
	6, // 7: rpkm67.file.image.v1.ObjectService.DeleteByKey:output_type -> rpkm67.file.image.v1.DeleteByKeyObjectResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpkm67_store_object_v1_object_proto_init() }
func file_rpkm67_store_object_v1_object_proto_init() {
	if File_rpkm67_store_object_v1_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpkm67_store_object_v1_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_store_object_v1_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByKeyObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_store_object_v1_object_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByKeyObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_store_object_v1_object_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_store_object_v1_object_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_store_object_v1_object_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteByKeyObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_store_object_v1_object_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteByKeyObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpkm67_store_object_v1_object_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpkm67_store_object_v1_object_proto_goTypes,
		DependencyIndexes: file_rpkm67_store_object_v1_object_proto_depIdxs,
		MessageInfos:      file_rpkm67_store_object_v1_object_proto_msgTypes,
	}.Build()
	File_rpkm67_store_object_v1_object_proto = out.File
	file_rpkm67_store_object_v1_object_proto_rawDesc = nil
	file_rpkm67_store_object_v1_object_proto_goTypes = nil
	file_rpkm67_store_object_v1_object_proto_depIdxs = nil
}
