// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: rpkm67/backend/group/v1/group.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GroupService_FindByUserId_FullMethodName  = "/rpkm67.backend.group.v1.GroupService/FindByUserId"
	GroupService_FindByToken_FullMethodName   = "/rpkm67.backend.group.v1.GroupService/FindByToken"
	GroupService_UpdateConfirm_FullMethodName = "/rpkm67.backend.group.v1.GroupService/UpdateConfirm"
	GroupService_Join_FullMethodName          = "/rpkm67.backend.group.v1.GroupService/Join"
	GroupService_DeleteMember_FullMethodName  = "/rpkm67.backend.group.v1.GroupService/DeleteMember"
	GroupService_Leave_FullMethodName         = "/rpkm67.backend.group.v1.GroupService/Leave"
)

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupServiceClient interface {
	FindByUserId(ctx context.Context, in *FindByUserIdGroupRequest, opts ...grpc.CallOption) (*FindByUserIdGroupResponse, error)
	FindByToken(ctx context.Context, in *FindByTokenGroupRequest, opts ...grpc.CallOption) (*FindByTokenGroupResponse, error)
	UpdateConfirm(ctx context.Context, in *UpdateConfirmGroupRequest, opts ...grpc.CallOption) (*UpdateConfirmGroupResponse, error)
	Join(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error)
	DeleteMember(ctx context.Context, in *DeleteMemberGroupRequest, opts ...grpc.CallOption) (*DeleteMemberGroupResponse, error)
	Leave(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error)
}

type groupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupServiceClient(cc grpc.ClientConnInterface) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) FindByUserId(ctx context.Context, in *FindByUserIdGroupRequest, opts ...grpc.CallOption) (*FindByUserIdGroupResponse, error) {
	out := new(FindByUserIdGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_FindByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) FindByToken(ctx context.Context, in *FindByTokenGroupRequest, opts ...grpc.CallOption) (*FindByTokenGroupResponse, error) {
	out := new(FindByTokenGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_FindByToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateConfirm(ctx context.Context, in *UpdateConfirmGroupRequest, opts ...grpc.CallOption) (*UpdateConfirmGroupResponse, error) {
	out := new(UpdateConfirmGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_UpdateConfirm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Join(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error) {
	out := new(JoinGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_Join_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DeleteMember(ctx context.Context, in *DeleteMemberGroupRequest, opts ...grpc.CallOption) (*DeleteMemberGroupResponse, error) {
	out := new(DeleteMemberGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_DeleteMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Leave(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error) {
	out := new(LeaveGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_Leave_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
// All implementations must embed UnimplementedGroupServiceServer
// for forward compatibility
type GroupServiceServer interface {
	FindByUserId(context.Context, *FindByUserIdGroupRequest) (*FindByUserIdGroupResponse, error)
	FindByToken(context.Context, *FindByTokenGroupRequest) (*FindByTokenGroupResponse, error)
	UpdateConfirm(context.Context, *UpdateConfirmGroupRequest) (*UpdateConfirmGroupResponse, error)
	Join(context.Context, *JoinGroupRequest) (*JoinGroupResponse, error)
	DeleteMember(context.Context, *DeleteMemberGroupRequest) (*DeleteMemberGroupResponse, error)
	Leave(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error)
	mustEmbedUnimplementedGroupServiceServer()
}

// UnimplementedGroupServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGroupServiceServer struct {
}

func (UnimplementedGroupServiceServer) FindByUserId(context.Context, *FindByUserIdGroupRequest) (*FindByUserIdGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByUserId not implemented")
}
func (UnimplementedGroupServiceServer) FindByToken(context.Context, *FindByTokenGroupRequest) (*FindByTokenGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByToken not implemented")
}
func (UnimplementedGroupServiceServer) UpdateConfirm(context.Context, *UpdateConfirmGroupRequest) (*UpdateConfirmGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfirm not implemented")
}
func (UnimplementedGroupServiceServer) Join(context.Context, *JoinGroupRequest) (*JoinGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedGroupServiceServer) DeleteMember(context.Context, *DeleteMemberGroupRequest) (*DeleteMemberGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMember not implemented")
}
func (UnimplementedGroupServiceServer) Leave(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedGroupServiceServer) mustEmbedUnimplementedGroupServiceServer() {}

// UnsafeGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServiceServer will
// result in compilation errors.
type UnsafeGroupServiceServer interface {
	mustEmbedUnimplementedGroupServiceServer()
}

func RegisterGroupServiceServer(s grpc.ServiceRegistrar, srv GroupServiceServer) {
	s.RegisterService(&GroupService_ServiceDesc, srv)
}

func _GroupService_FindByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByUserIdGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).FindByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_FindByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).FindByUserId(ctx, req.(*FindByUserIdGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_FindByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByTokenGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).FindByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_FindByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).FindByToken(ctx, req.(*FindByTokenGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfirmGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UpdateConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateConfirm(ctx, req.(*UpdateConfirmGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Join(ctx, req.(*JoinGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_DeleteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DeleteMember(ctx, req.(*DeleteMemberGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Leave(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupService_ServiceDesc is the grpc.ServiceDesc for GroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpkm67.backend.group.v1.GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByUserId",
			Handler:    _GroupService_FindByUserId_Handler,
		},
		{
			MethodName: "FindByToken",
			Handler:    _GroupService_FindByToken_Handler,
		},
		{
			MethodName: "UpdateConfirm",
			Handler:    _GroupService_UpdateConfirm_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _GroupService_Join_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _GroupService_DeleteMember_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _GroupService_Leave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpkm67/backend/group/v1/group.proto",
}
