// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpkm67/backend/selection/v1/selection.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId string   `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	BaanIds []string `protobuf:"bytes,3,rep,name=baanIds,proto3" json:"baanIds,omitempty"`
}

func (x *Selection) Reset() {
	*x = Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{0}
}

func (x *Selection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Selection) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Selection) GetBaanIds() []string {
	if x != nil {
		return x.BaanIds
	}
	return nil
}

// Create
type CreateSelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	BaanIds []string `protobuf:"bytes,2,rep,name=baanIds,proto3" json:"baanIds,omitempty"`
}

func (x *CreateSelectionRequest) Reset() {
	*x = CreateSelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelectionRequest) ProtoMessage() {}

func (x *CreateSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSelectionRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSelectionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateSelectionRequest) GetBaanIds() []string {
	if x != nil {
		return x.BaanIds
	}
	return nil
}

type CreateSelectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selection *Selection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
}

func (x *CreateSelectionResponse) Reset() {
	*x = CreateSelectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelectionResponse) ProtoMessage() {}

func (x *CreateSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelectionResponse.ProtoReflect.Descriptor instead.
func (*CreateSelectionResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSelectionResponse) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

// FindByGroupId
type FindByGroupIdSelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannId string `protobuf:"bytes,1,opt,name=bannId,proto3" json:"bannId,omitempty"`
}

func (x *FindByGroupIdSelectionRequest) Reset() {
	*x = FindByGroupIdSelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByGroupIdSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByGroupIdSelectionRequest) ProtoMessage() {}

func (x *FindByGroupIdSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByGroupIdSelectionRequest.ProtoReflect.Descriptor instead.
func (*FindByGroupIdSelectionRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{3}
}

func (x *FindByGroupIdSelectionRequest) GetBannId() string {
	if x != nil {
		return x.BannId
	}
	return ""
}

type FindByGroupIdSelectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selection *Selection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
}

func (x *FindByGroupIdSelectionResponse) Reset() {
	*x = FindByGroupIdSelectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByGroupIdSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByGroupIdSelectionResponse) ProtoMessage() {}

func (x *FindByGroupIdSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByGroupIdSelectionResponse.ProtoReflect.Descriptor instead.
func (*FindByGroupIdSelectionResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{4}
}

func (x *FindByGroupIdSelectionResponse) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

// Update
type UpdateSelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selection *Selection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
}

func (x *UpdateSelectionRequest) Reset() {
	*x = UpdateSelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSelectionRequest) ProtoMessage() {}

func (x *UpdateSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSelectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSelectionRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSelectionRequest) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

type UpdateSelectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateSelectionResponse) Reset() {
	*x = UpdateSelectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSelectionResponse) ProtoMessage() {}

func (x *UpdateSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSelectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSelectionResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSelectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpkm67_backend_selection_v1_selection_proto protoreflect.FileDescriptor

var file_rpkm67_backend_selection_v1_selection_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x72,
	0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x4f, 0x0a, 0x09, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x4c, 0x0a, 0x16, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x5f, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x1d, 0x46, 0x69,
	0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x61, 0x6e, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x6e,
	0x6e, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x1e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36,
	0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5e, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36,
	0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x17, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x32, 0x8d, 0x03, 0x0a, 0x10, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x33, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x8a, 0x01, 0x0a,
	0x0d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x3a,
	0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3b, 0x2e, 0x72, 0x70, 0x6b,
	0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x33, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36,
	0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x1d, 0x5a, 0x1b, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpkm67_backend_selection_v1_selection_proto_rawDescOnce sync.Once
	file_rpkm67_backend_selection_v1_selection_proto_rawDescData = file_rpkm67_backend_selection_v1_selection_proto_rawDesc
)

func file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP() []byte {
	file_rpkm67_backend_selection_v1_selection_proto_rawDescOnce.Do(func() {
		file_rpkm67_backend_selection_v1_selection_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpkm67_backend_selection_v1_selection_proto_rawDescData)
	})
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescData
}

var file_rpkm67_backend_selection_v1_selection_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpkm67_backend_selection_v1_selection_proto_goTypes = []interface{}{
	(*Selection)(nil),                      // 0: rpkm67.backend.selection.v1.Selection
	(*CreateSelectionRequest)(nil),         // 1: rpkm67.backend.selection.v1.CreateSelectionRequest
	(*CreateSelectionResponse)(nil),        // 2: rpkm67.backend.selection.v1.CreateSelectionResponse
	(*FindByGroupIdSelectionRequest)(nil),  // 3: rpkm67.backend.selection.v1.FindByGroupIdSelectionRequest
	(*FindByGroupIdSelectionResponse)(nil), // 4: rpkm67.backend.selection.v1.FindByGroupIdSelectionResponse
	(*UpdateSelectionRequest)(nil),         // 5: rpkm67.backend.selection.v1.UpdateSelectionRequest
	(*UpdateSelectionResponse)(nil),        // 6: rpkm67.backend.selection.v1.UpdateSelectionResponse
}
var file_rpkm67_backend_selection_v1_selection_proto_depIdxs = []int32{
	0, // 0: rpkm67.backend.selection.v1.CreateSelectionResponse.selection:type_name -> rpkm67.backend.selection.v1.Selection
	0, // 1: rpkm67.backend.selection.v1.FindByGroupIdSelectionResponse.selection:type_name -> rpkm67.backend.selection.v1.Selection
	0, // 2: rpkm67.backend.selection.v1.UpdateSelectionRequest.selection:type_name -> rpkm67.backend.selection.v1.Selection
	1, // 3: rpkm67.backend.selection.v1.SelectionService.Create:input_type -> rpkm67.backend.selection.v1.CreateSelectionRequest
	3, // 4: rpkm67.backend.selection.v1.SelectionService.FindByGroupId:input_type -> rpkm67.backend.selection.v1.FindByGroupIdSelectionRequest
	5, // 5: rpkm67.backend.selection.v1.SelectionService.Update:input_type -> rpkm67.backend.selection.v1.UpdateSelectionRequest
	2, // 6: rpkm67.backend.selection.v1.SelectionService.Create:output_type -> rpkm67.backend.selection.v1.CreateSelectionResponse
	4, // 7: rpkm67.backend.selection.v1.SelectionService.FindByGroupId:output_type -> rpkm67.backend.selection.v1.FindByGroupIdSelectionResponse
	6, // 8: rpkm67.backend.selection.v1.SelectionService.Update:output_type -> rpkm67.backend.selection.v1.UpdateSelectionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpkm67_backend_selection_v1_selection_proto_init() }
func file_rpkm67_backend_selection_v1_selection_proto_init() {
	if File_rpkm67_backend_selection_v1_selection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSelectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByGroupIdSelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByGroupIdSelectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSelectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpkm67_backend_selection_v1_selection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpkm67_backend_selection_v1_selection_proto_goTypes,
		DependencyIndexes: file_rpkm67_backend_selection_v1_selection_proto_depIdxs,
		MessageInfos:      file_rpkm67_backend_selection_v1_selection_proto_msgTypes,
	}.Build()
	File_rpkm67_backend_selection_v1_selection_proto = out.File
	file_rpkm67_backend_selection_v1_selection_proto_rawDesc = nil
	file_rpkm67_backend_selection_v1_selection_proto_goTypes = nil
	file_rpkm67_backend_selection_v1_selection_proto_depIdxs = nil
}
