// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpkm67/backend/selection/v1/selection.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Selection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId string `protobuf:"bytes,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	BaanId  string `protobuf:"bytes,3,opt,name=baanId,proto3" json:"baanId,omitempty"`
	Order   int32  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *Selection) Reset() {
	*x = Selection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{0}
}

func (x *Selection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Selection) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Selection) GetBaanId() string {
	if x != nil {
		return x.BaanId
	}
	return ""
}

func (x *Selection) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type BaanCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaanId string `protobuf:"bytes,1,opt,name=baanId,proto3" json:"baanId,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BaanCount) Reset() {
	*x = BaanCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaanCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaanCount) ProtoMessage() {}

func (x *BaanCount) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaanCount.ProtoReflect.Descriptor instead.
func (*BaanCount) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{1}
}

func (x *BaanCount) GetBaanId() string {
	if x != nil {
		return x.BaanId
	}
	return ""
}

func (x *BaanCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Create
type CreateSelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	BaanId  string `protobuf:"bytes,2,opt,name=baanId,proto3" json:"baanId,omitempty"`
	Order   int32  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *CreateSelectionRequest) Reset() {
	*x = CreateSelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelectionRequest) ProtoMessage() {}

func (x *CreateSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSelectionRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSelectionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateSelectionRequest) GetBaanId() string {
	if x != nil {
		return x.BaanId
	}
	return ""
}

func (x *CreateSelectionRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type CreateSelectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selection *Selection `protobuf:"bytes,1,opt,name=selection,proto3" json:"selection,omitempty"`
}

func (x *CreateSelectionResponse) Reset() {
	*x = CreateSelectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSelectionResponse) ProtoMessage() {}

func (x *CreateSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSelectionResponse.ProtoReflect.Descriptor instead.
func (*CreateSelectionResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSelectionResponse) GetSelection() *Selection {
	if x != nil {
		return x.Selection
	}
	return nil
}

// FindByGroupId
type FindByGroupIdSelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *FindByGroupIdSelectionRequest) Reset() {
	*x = FindByGroupIdSelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByGroupIdSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByGroupIdSelectionRequest) ProtoMessage() {}

func (x *FindByGroupIdSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByGroupIdSelectionRequest.ProtoReflect.Descriptor instead.
func (*FindByGroupIdSelectionRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{4}
}

func (x *FindByGroupIdSelectionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type FindByGroupIdSelectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selections []*Selection `protobuf:"bytes,1,rep,name=selections,proto3" json:"selections,omitempty"`
}

func (x *FindByGroupIdSelectionResponse) Reset() {
	*x = FindByGroupIdSelectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindByGroupIdSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByGroupIdSelectionResponse) ProtoMessage() {}

func (x *FindByGroupIdSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByGroupIdSelectionResponse.ProtoReflect.Descriptor instead.
func (*FindByGroupIdSelectionResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{5}
}

func (x *FindByGroupIdSelectionResponse) GetSelections() []*Selection {
	if x != nil {
		return x.Selections
	}
	return nil
}

// Delete
type DeleteSelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *DeleteSelectionRequest) Reset() {
	*x = DeleteSelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSelectionRequest) ProtoMessage() {}

func (x *DeleteSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSelectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSelectionRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSelectionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type DeleteSelectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteSelectionResponse) Reset() {
	*x = DeleteSelectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSelectionResponse) ProtoMessage() {}

func (x *DeleteSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSelectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSelectionResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSelectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CountByBaanId
type CountByBaanIdSelectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CountByBaanIdSelectionRequest) Reset() {
	*x = CountByBaanIdSelectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountByBaanIdSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountByBaanIdSelectionRequest) ProtoMessage() {}

func (x *CountByBaanIdSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountByBaanIdSelectionRequest.ProtoReflect.Descriptor instead.
func (*CountByBaanIdSelectionRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{8}
}

type CountByBaanIdSelectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaanCounts []*BaanCount `protobuf:"bytes,1,rep,name=baanCounts,proto3" json:"baanCounts,omitempty"`
}

func (x *CountByBaanIdSelectionResponse) Reset() {
	*x = CountByBaanIdSelectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountByBaanIdSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountByBaanIdSelectionResponse) ProtoMessage() {}

func (x *CountByBaanIdSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_selection_v1_selection_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountByBaanIdSelectionResponse.ProtoReflect.Descriptor instead.
func (*CountByBaanIdSelectionResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP(), []int{9}
}

func (x *CountByBaanIdSelectionResponse) GetBaanCounts() []*BaanCount {
	if x != nil {
		return x.BaanCounts
	}
	return nil
}

var File_rpkm67_backend_selection_v1_selection_proto protoreflect.FileDescriptor

var file_rpkm67_backend_selection_v1_selection_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x72,
	0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x63, 0x0a, 0x09, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22,
	0x39, 0x0a, 0x09, 0x42, 0x61, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61,
	0x61, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x16, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x5f, 0x0a, 0x17,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x70, 0x6b,
	0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a,
	0x1d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x1e, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0a, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26,
	0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x1f, 0x0a, 0x1d, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x42, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x68, 0x0a, 0x1e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x42, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x0a, 0x62, 0x61, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x61, 0x61, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0a, 0x62, 0x61, 0x61, 0x6e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x32, 0x9a, 0x04, 0x0a, 0x10, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x33, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x72, 0x70, 0x6b,
	0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x8a, 0x01, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x12, 0x3a, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x3b, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x75, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x33, 0x2e, 0x72, 0x70, 0x6b, 0x6d,
	0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34,
	0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x8a, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x79, 0x42, 0x61, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x3a, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36,
	0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x42, 0x61,
	0x61, 0x6e, 0x49, 0x64, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x3b, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x42, 0x61, 0x61, 0x6e, 0x49, 0x64,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x1d, 0x5a, 0x1b, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpkm67_backend_selection_v1_selection_proto_rawDescOnce sync.Once
	file_rpkm67_backend_selection_v1_selection_proto_rawDescData = file_rpkm67_backend_selection_v1_selection_proto_rawDesc
)

func file_rpkm67_backend_selection_v1_selection_proto_rawDescGZIP() []byte {
	file_rpkm67_backend_selection_v1_selection_proto_rawDescOnce.Do(func() {
		file_rpkm67_backend_selection_v1_selection_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpkm67_backend_selection_v1_selection_proto_rawDescData)
	})
	return file_rpkm67_backend_selection_v1_selection_proto_rawDescData
}

var file_rpkm67_backend_selection_v1_selection_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpkm67_backend_selection_v1_selection_proto_goTypes = []interface{}{
	(*Selection)(nil),                      // 0: rpkm67.backend.selection.v1.Selection
	(*BaanCount)(nil),                      // 1: rpkm67.backend.selection.v1.BaanCount
	(*CreateSelectionRequest)(nil),         // 2: rpkm67.backend.selection.v1.CreateSelectionRequest
	(*CreateSelectionResponse)(nil),        // 3: rpkm67.backend.selection.v1.CreateSelectionResponse
	(*FindByGroupIdSelectionRequest)(nil),  // 4: rpkm67.backend.selection.v1.FindByGroupIdSelectionRequest
	(*FindByGroupIdSelectionResponse)(nil), // 5: rpkm67.backend.selection.v1.FindByGroupIdSelectionResponse
	(*DeleteSelectionRequest)(nil),         // 6: rpkm67.backend.selection.v1.DeleteSelectionRequest
	(*DeleteSelectionResponse)(nil),        // 7: rpkm67.backend.selection.v1.DeleteSelectionResponse
	(*CountByBaanIdSelectionRequest)(nil),  // 8: rpkm67.backend.selection.v1.CountByBaanIdSelectionRequest
	(*CountByBaanIdSelectionResponse)(nil), // 9: rpkm67.backend.selection.v1.CountByBaanIdSelectionResponse
}
var file_rpkm67_backend_selection_v1_selection_proto_depIdxs = []int32{
	0, // 0: rpkm67.backend.selection.v1.CreateSelectionResponse.selection:type_name -> rpkm67.backend.selection.v1.Selection
	0, // 1: rpkm67.backend.selection.v1.FindByGroupIdSelectionResponse.selections:type_name -> rpkm67.backend.selection.v1.Selection
	1, // 2: rpkm67.backend.selection.v1.CountByBaanIdSelectionResponse.baanCounts:type_name -> rpkm67.backend.selection.v1.BaanCount
	2, // 3: rpkm67.backend.selection.v1.SelectionService.Create:input_type -> rpkm67.backend.selection.v1.CreateSelectionRequest
	4, // 4: rpkm67.backend.selection.v1.SelectionService.FindByGroupId:input_type -> rpkm67.backend.selection.v1.FindByGroupIdSelectionRequest
	6, // 5: rpkm67.backend.selection.v1.SelectionService.Delete:input_type -> rpkm67.backend.selection.v1.DeleteSelectionRequest
	8, // 6: rpkm67.backend.selection.v1.SelectionService.CountByBaanId:input_type -> rpkm67.backend.selection.v1.CountByBaanIdSelectionRequest
	3, // 7: rpkm67.backend.selection.v1.SelectionService.Create:output_type -> rpkm67.backend.selection.v1.CreateSelectionResponse
	5, // 8: rpkm67.backend.selection.v1.SelectionService.FindByGroupId:output_type -> rpkm67.backend.selection.v1.FindByGroupIdSelectionResponse
	7, // 9: rpkm67.backend.selection.v1.SelectionService.Delete:output_type -> rpkm67.backend.selection.v1.DeleteSelectionResponse
	9, // 10: rpkm67.backend.selection.v1.SelectionService.CountByBaanId:output_type -> rpkm67.backend.selection.v1.CountByBaanIdSelectionResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpkm67_backend_selection_v1_selection_proto_init() }
func file_rpkm67_backend_selection_v1_selection_proto_init() {
	if File_rpkm67_backend_selection_v1_selection_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Selection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaanCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSelectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByGroupIdSelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindByGroupIdSelectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSelectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountByBaanIdSelectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_selection_v1_selection_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountByBaanIdSelectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpkm67_backend_selection_v1_selection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpkm67_backend_selection_v1_selection_proto_goTypes,
		DependencyIndexes: file_rpkm67_backend_selection_v1_selection_proto_depIdxs,
		MessageInfos:      file_rpkm67_backend_selection_v1_selection_proto_msgTypes,
	}.Build()
	File_rpkm67_backend_selection_v1_selection_proto = out.File
	file_rpkm67_backend_selection_v1_selection_proto_rawDesc = nil
	file_rpkm67_backend_selection_v1_selection_proto_goTypes = nil
	file_rpkm67_backend_selection_v1_selection_proto_depIdxs = nil
}
