// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpkm67/backend/pin/v1/pin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId string `protobuf:"bytes,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Code       string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Pin) Reset() {
	*x = Pin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP(), []int{0}
}

func (x *Pin) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *Pin) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// FindAll
type FindAllPinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllPinRequest) Reset() {
	*x = FindAllPinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPinRequest) ProtoMessage() {}

func (x *FindAllPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPinRequest.ProtoReflect.Descriptor instead.
func (*FindAllPinRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP(), []int{1}
}

type FindAllPinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pins []*Pin `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
}

func (x *FindAllPinResponse) Reset() {
	*x = FindAllPinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPinResponse) ProtoMessage() {}

func (x *FindAllPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPinResponse.ProtoReflect.Descriptor instead.
func (*FindAllPinResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllPinResponse) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

// ResetPin
type ResetPinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId string `protobuf:"bytes,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
}

func (x *ResetPinRequest) Reset() {
	*x = ResetPinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPinRequest) ProtoMessage() {}

func (x *ResetPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPinRequest.ProtoReflect.Descriptor instead.
func (*ResetPinRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP(), []int{3}
}

func (x *ResetPinRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

type ResetPinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ResetPinResponse) Reset() {
	*x = ResetPinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPinResponse) ProtoMessage() {}

func (x *ResetPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPinResponse.ProtoReflect.Descriptor instead.
func (*ResetPinResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP(), []int{4}
}

func (x *ResetPinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CheckPin
type CheckPinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityId string `protobuf:"bytes,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Code       string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CheckPinRequest) Reset() {
	*x = CheckPinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPinRequest) ProtoMessage() {}

func (x *CheckPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPinRequest.ProtoReflect.Descriptor instead.
func (*CheckPinRequest) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP(), []int{5}
}

func (x *CheckPinRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *CheckPinRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CheckPinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMatch bool `protobuf:"varint,1,opt,name=isMatch,proto3" json:"isMatch,omitempty"`
}

func (x *CheckPinResponse) Reset() {
	*x = CheckPinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPinResponse) ProtoMessage() {}

func (x *CheckPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm67_backend_pin_v1_pin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPinResponse.ProtoReflect.Descriptor instead.
func (*CheckPinResponse) Descriptor() ([]byte, []int) {
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPinResponse) GetIsMatch() bool {
	if x != nil {
		return x.IsMatch
	}
	return false
}

var File_rpkm67_backend_pin_v1_pin_proto protoreflect.FileDescriptor

var file_rpkm67_backend_pin_v1_pin_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x39, 0x0a, 0x03, 0x50, 0x69, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x04, 0x70, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72,
	0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x73, 0x22, 0x31,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x22, 0x2c, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x45, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x32, 0xac, 0x02, 0x0a, 0x0a, 0x50, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x28,
	0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x70, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36,
	0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x69,
	0x6e, 0x12, 0x26, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x72, 0x70, 0x6b, 0x6d,
	0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x69, 0x6e,
	0x12, 0x26, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36,
	0x37, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x37, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpkm67_backend_pin_v1_pin_proto_rawDescOnce sync.Once
	file_rpkm67_backend_pin_v1_pin_proto_rawDescData = file_rpkm67_backend_pin_v1_pin_proto_rawDesc
)

func file_rpkm67_backend_pin_v1_pin_proto_rawDescGZIP() []byte {
	file_rpkm67_backend_pin_v1_pin_proto_rawDescOnce.Do(func() {
		file_rpkm67_backend_pin_v1_pin_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpkm67_backend_pin_v1_pin_proto_rawDescData)
	})
	return file_rpkm67_backend_pin_v1_pin_proto_rawDescData
}

var file_rpkm67_backend_pin_v1_pin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpkm67_backend_pin_v1_pin_proto_goTypes = []interface{}{
	(*Pin)(nil),                // 0: rpkm67.backend.pin.v1.Pin
	(*FindAllPinRequest)(nil),  // 1: rpkm67.backend.pin.v1.FindAllPinRequest
	(*FindAllPinResponse)(nil), // 2: rpkm67.backend.pin.v1.FindAllPinResponse
	(*ResetPinRequest)(nil),    // 3: rpkm67.backend.pin.v1.ResetPinRequest
	(*ResetPinResponse)(nil),   // 4: rpkm67.backend.pin.v1.ResetPinResponse
	(*CheckPinRequest)(nil),    // 5: rpkm67.backend.pin.v1.CheckPinRequest
	(*CheckPinResponse)(nil),   // 6: rpkm67.backend.pin.v1.CheckPinResponse
}
var file_rpkm67_backend_pin_v1_pin_proto_depIdxs = []int32{
	0, // 0: rpkm67.backend.pin.v1.FindAllPinResponse.pins:type_name -> rpkm67.backend.pin.v1.Pin
	1, // 1: rpkm67.backend.pin.v1.PinService.FindAll:input_type -> rpkm67.backend.pin.v1.FindAllPinRequest
	3, // 2: rpkm67.backend.pin.v1.PinService.ResetPin:input_type -> rpkm67.backend.pin.v1.ResetPinRequest
	5, // 3: rpkm67.backend.pin.v1.PinService.CheckPin:input_type -> rpkm67.backend.pin.v1.CheckPinRequest
	2, // 4: rpkm67.backend.pin.v1.PinService.FindAll:output_type -> rpkm67.backend.pin.v1.FindAllPinResponse
	4, // 5: rpkm67.backend.pin.v1.PinService.ResetPin:output_type -> rpkm67.backend.pin.v1.ResetPinResponse
	6, // 6: rpkm67.backend.pin.v1.PinService.CheckPin:output_type -> rpkm67.backend.pin.v1.CheckPinResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpkm67_backend_pin_v1_pin_proto_init() }
func file_rpkm67_backend_pin_v1_pin_proto_init() {
	if File_rpkm67_backend_pin_v1_pin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpkm67_backend_pin_v1_pin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_pin_v1_pin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_pin_v1_pin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_pin_v1_pin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetPinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_pin_v1_pin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetPinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_pin_v1_pin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm67_backend_pin_v1_pin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckPinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpkm67_backend_pin_v1_pin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpkm67_backend_pin_v1_pin_proto_goTypes,
		DependencyIndexes: file_rpkm67_backend_pin_v1_pin_proto_depIdxs,
		MessageInfos:      file_rpkm67_backend_pin_v1_pin_proto_msgTypes,
	}.Build()
	File_rpkm67_backend_pin_v1_pin_proto = out.File
	file_rpkm67_backend_pin_v1_pin_proto_rawDesc = nil
	file_rpkm67_backend_pin_v1_pin_proto_goTypes = nil
	file_rpkm67_backend_pin_v1_pin_proto_depIdxs = nil
}
